.github/workflows/ci.yml
Let's see if updating to the latest commit fixes the issues we've been seeing.
=> Update Publish Symbols Action

samples/rxfilter/rxfilter.c, samples/rxfilter/rxfilter.vcxproj, xdp.sln
Create a simple RX filtering tool to resolve #32.
=> Add rxfilter sample

docs/usage.md, tools/log.ps1, tools/prepare-machine.ps1, tools/xdptrace.wprp
Resolve #70 by simplifying common logging use cases and adding documentation.
=> Improve logging experience

tools/common.ps1, tools/prepare-machine.ps1
We see intermittent download failures in CI; attempt to retry a few times if any download fails.
=> Powershell: retry downloads

xdp.props
Bump up the version to 0.16.6.
=> Bump up XDP version to 0.16.6

src/xdp/ebpfextension.c, src/xdp/packages.config, src/xdp/program.c, tools/common.ps1, tools/prepare-machine.ps1, xdp.props
Our eBPF binaries are now several weeks and one minor version number old, so bump everything up to the latest and greatest.
=> Upgrade to the latest prerelease build of eBPF

src/xdp/ebpf_private_extension.h, src/xdp/precomp.h, src/xdp/program.c
Work towards resolving #174: the eBPF project has published some missing extension definitions.
=> Consume new eBPF extension definitions

tools/common.ps1, tools/prepare-machine.ps1
=> Update to a newer eBPF 0.7.0 build

.azure/scripts/agent-functionaltest/Setup.ps1, .azure/scripts/agent-spinxsktest/Setup.ps1
Collect both user and kernel mode address spaces in Azure pipelines. This is already deployed.
#201
=> Collect full kernel dumps in Azure pipelines

src/xdp/ebpfextension.c, src/xdp/ebpfextension.h, src/xdp/packages.config, src/xdp/program.c, src/xdp/program.h, test/bpf/bpf.vcxproj, tools/common.ps1, tools/prepare-machine.ps1, xdp.props
Ingest eBPF 0.9.0. Consume new and improved APIs.
Resolves #170
=> Ingest eBPF 0.9.0

test/common/inc/fniotypes.h, test/functional/lib/tests.cpp, test/functional/mp/sys/adapter.c, test/functional/mp/sys/miniport.c, test/functional/mp/sys/miniport.h, test/functional/mp/sys/oid.c, test/functional/mp/sys/oid.h
Breaking the QEO work down into parts, add support for direct OID interface and method OID request types to XDPFNMP.
=> Add XDPFNMP support for direct OIDs

xdp.props
Update after previous release.
=> Bumb XDP Patch Version

docs/threat-model.md
Mostly just an outline right now.
=> Outline of an Initial Threat Model

.gitmodules, src/xdplwf/offloadqeo.c, src/xdplwf/precomp.h, test/functional/lib/tests.cpp, test/functional/lib/xdptests.vcxproj, test/functional/mp/sys/oid.c, xdp.cpp.kernel.props
1. Consume new NDIS OID definition.
2. Conditionally fall back to prototype OID definition.
3. Update tests, which only can validate the prototype OID right now.
4. Consume rename of quic-offloads -> net-offloads.
=> Consume new NDIS OID definition and fall back to IPSec prototype OID

docs/threat-model.md
Add some more detail to our threat model.
=> Add some more detail to our threat model

tools/xdptrace.wprp
Add more diagnostics to root cause the still-flaky #252
=> Enable OS component tracing in functional tests

tools/setup.ps1
=> catch eBPF uninstall hangs

.github/workflows/ci.yml
=> Use 1ES hosted pools for GitHub actions

tools/setup.ps1
We're hitting another issue in CI where the WMI query to find the eBPF installation GUID is hanging indefinitely. Since we know the version of eBPF that we installed, just use the MSI directly. This is not necessarily great for some manual testing scenarios, but it is more predictable, and should hopefully be more reliable in CI.
Fixes #254
=> Avoid WMI query during eBPF uninstall

.azure/scripts/clean-artifacts.ps1, .azure/templates/tests.yml, .github/workflows/ci.yml, tools/build.ps1, tools/check-drivers.ps1, tools/common.ps1, tools/functional.ps1, tools/log.ps1, tools/prepare-machine.ps1, tools/rxfilter.ps1, tools/setup.ps1, tools/sign.ps1, tools/spinxsk.ps1, tools/sync-mirror.ps1
=> Add functional test watchdog

.github/workflows/ci.yml
When the Actions were onboarded, pwsh (PowerShell Core) was used; this project relies only on plain PowerShell.
=> Use plain PowerShell in GitHub Actions

.github/workflows/ci.yml, tools/xskperf.ps1
Continue progress towards #256 by onboarding existing TX-inspect, RX-inject, and baseline Winsock/RIO comparisons.
=> add more perf coverage

test/functional/lib/tests.cpp
We don't have visibility into the system commands being run in functional tests, so fix that.
=> Log system commands in functional tests

tools/common.ps1, tools/log.ps1, tools/prepare-machine.ps1, tools/setup.ps1, tools/sign.ps1, tools/spinxsk.ps1, tools/xskperf.ps1
Ensure each XDP commit depends on a specific dependency version
=> Depend on specific build of corenet-ci repo

samples/rxfilter/rxfilter.c, test/spinxsk/spinxsk.c, test/xskbench/xskbench.c
I was taking a quick peek at `rxfilter.c` and spotted some questionable validation of `ArgC`. This appears to be a widespread copy/pasta from a flawed original piece of code. Fix it all.
=> Don't exceed command line argument count

samples/xskfwd/xskfwd.c, samples/xskfwd/xskfwd.vcxproj, tools/create-devkit.ps1, xdp.sln
We need a simple example of AF_XDP socket usage. `xskbench.exe` is powerful and demonstrates many advanced features, but obscures the basic mechanics of AF_XDP.
=> Add simple AF_XDP sample

tools/prepare-machine.ps1
The prepare-machine script doesn't work if your current directory isn't the xdp directory. Fix that.
=> Invoke prepare-machine from anywhere

chart.js
Updates the dashboard to chart (by default) grouped by test type (`RX-BUSY-2048chunksize-64iosize-FNDIS`) instead of the technology (`XDPMP-NATIVE`), but still allows for the old model by setting `?byTest=0` in the URL.
=> Charts by Test Type

.github/workflows/ci.yml
The job timeouts are still not taking effect, and GitHub is still complaining about the syntax, so remove the variables and see if that helps.
=> Try again with GitHub actions timeouts

docs/usage.md, tools/setup.ps1
=> Add MSI documentation

tools/xskperf.ps1, tools/xskperfsuite.ps1
Fix more errors in the CI perf scripts that were caught when setting strict mode.
=> More perf script fixes

published/external/afxdp.h, published/external/afxdp_helper.h, samples/xskfwd/xskfwd.c, src/xdp/xsk.c, src/xdpapi/afxdp.c, test/functional/lib/tests.cpp, test/spinxsk/spinxsk.c, test/xskbench/xskbench.c
Resolves #325 and wore out my F2 key.
=> Consistently use PascalCase for fields and variables in published API

tools/common.ps1, tools/setup.ps1
=> Improve eBPF uninstall timeout diagnostics

docs/afxdp.md, docs/api/XSK_BUFFER_ADDRESS.md, docs/api/XSK_BUFFER_DESCRIPTOR.md, published/external/afxdp.h, published/external/afxdp_helper.h, samples/xskfwd/xskfwd.c, src/xdp/xsk.c, test/functional/lib/tests.cpp, test/spinxsk/spinxsk.c, test/xskbench/xskbench.c
=> convert XSK buffer types from macro-based bit values to plain C bitfields

src/xdp.props
We're getting very close to a 1.0 release, so bump our minor version number and reset the patch.
=> Bump minor release

src/xdp.props
Bump the patch number for main.
=> Bump patch number

docs/afxdp.md, docs/faq.md
=> add a few more docs

src/xdp.cpp.props
This flag is required by the HLK.
=> Set CET flag

.azure/.gdnsuppress, .azure/OneBranch.Official.yml, .azure/OneBranch.PullRequest.yml, .azure/templates/build.yml
Tested internally via mscodehub first.
=> OneBranch Build Support

.azure/OneBranch.Official.yml
Duplicate use of `globalSdl` fix.
=> Fix Official OneBranch Pipeline

docs/api/XdpOpenApi.md, published/external/xdpapi.h, samples/rxfilter/rxfilter.c, samples/xskfwd/xskfwd.c, src/xdp.props, src/xdpapi/xdpapi.c, test/functional/lib/tests.cpp, test/rssconfig/rssconfig.c, test/spinxsk/spinxsk.c, test/xskbench/xskbench.c
=> Bump versions for 1.0 release

docs/release.md
Document release and support dates for v1.0
=> Mention v1.0 in Release Docs

tools/create-devkit.ps1
Reduce the duplicate and redundant artifacts in the dev kit. The MSI is available as a standalone download.
=> reduce artifacts in devkit

tools/create-devkit.ps1
=> cherry-pick reduce artifacts in devkit (#372) to release/1.0

docs/development.md
WiX is required for building the project
=> Add WiX requirement for building the project in the documentation

.github/workflows/ci.yml, tools/prepare-machine.ps1, tools/two-machine-perf.ps1
This adds a new job to trigger a perf run in the netperf repository. For now, it does a very simple 2-machine test. Future PRs will improve the coverage here.
=> Add NetPerf Trigger

tools/setup.ps1
While working on another project based on this script, I noticed a typo and fixed it here, too.
=> fix typo in eBPF setup script

.github/workflows/ci.yml
Merge #433 and #430 into one branch since the upload and download actions seem to have a dependency on each other.
=> Merge two dependabot artifact PRs

.azure/templates/build.yml, .github/workflows/ci.yml, src/xdp.props, src/xdpinstaller/packages.config, src/xdpinstaller/xdpinstaller.wixproj, tools/build.ps1, tools/create-installer.ps1
CVE-2024-24810 is fixed in WiX 3.14.0
=> Update to WiX 3.14.0

.azure/templates/build.yml, .github/workflows/ci.yml, src/xdp.props, src/xdpinstaller/packages.config, src/xdpinstaller/xdpinstaller.wixproj, tools/build.ps1
=> [release/1.0] Update to WiX 3.14.0 (#461)

.azure/OneBranch.PullRequest.yml
Compliance requires SBOMs everywhere.
=> Create an SBOM in OneBranch PR build pipeline

src/xdp.props, src/xdpinstaller/packages.config
Addresses a recent CVE in WiX v3.14.0.
=> Increment WiX Installer Dependency Version

src/xdp.props, src/xdpinstaller/packages.config
=> Increment WiX Installer Dependency Version (#481)

src/bpfexport/bpfexport.c, src/xdp.props, src/xdp/ebpfextension.h, src/xdp/ebpfstore.h, src/xdp/packages.config, src/xdp/program.c, tools/common.ps1, tools/prepare-machine.ps1
Update ebpf-for-windows version to v0.15.1
=> Update ebpf-for-windows version to v0.15.1

docs/development.md
I had to re-create a development machine and realized our documentation has gone stale.
=> Update development guide, which has gone stale

samples/rxfilter/rxfilter.c, test/bpf/bpf.vcxproj, test/xskbench/xskbench.c, tools/common.ps1, tools/prepare-machine.ps1, tools/setup.ps1, tools/two-machine-perf.ps1
Add some more perf tests to the latest perf test framework. Also squash a few test/infra bugs.
=> Improve XDP performance tests

tools/xdptrace.wprp
The GUID was missing a character.
=> Fix AFD trace GUID

tools/common.ps1
Update to latest version of https://github.com/microsoft/corenet-ci.
=> update to latest corenet-ci version

test/functional/taef/tests.cpp
Progress towards #526. Tag tests for prerelease/experimental features that are subject to breaking changes.
=> Set test attribute for prerelease feature tests

test/functional/taef/tests.cpp
Work towards #526 by cherry-picking #542
=> release/1.0: set taef attribute for prerelease feature tests (#542)

test/functional/lib/tests.cpp
=> fix build for GenericRxEbpfFragments

test/functional/taef/tests.cpp
=> update filtering logic for prerelease tests

.github/workflows/ci.yml
#555 uses a third-party action, so apply principle of least privilege.
=> deny all permissions for completion check

test/functional/lib/tests.cpp
While running new RSC tests, I hit a flaky test: it took over one second for NDIS to re-attach the XDPLWF to the stack after an MTU change. This is outside of our control (the logs did not show any delays in any XDP or test code) so simply treat both the detach and the re-attach as being a partial restart from a timeout point-of-view.
=> improve reliability of GenericTxMtu test

docs/development.md
The existing instructions are incomplete for compiling XDP locally.
=> Update instructions in development.md

src/xdpinstaller/product.wxs
=> install xdptrace.wprp with MSI

.github/workflows/ci.yml, tools/merge-artifacts.ps1
Our "downlevel" tests became uplevel tests after #571 
Resolves #581
=> make downlevel tests actually run

tools/common.ps1, tools/prepare-machine.ps1, tools/setup.ps1
=> remove ebpf JIT and use strongly versioned MSI filename

src/nuget/nuget.vcxproj
=> fix nuget build in onebranch

tools/common.ps1, tools/create-test-archive.ps1, tools/update-nuspec.ps1
=> append prerelease string to nuget version outside of release builds

.github/workflows/ci.yml
Build XDP using onebranch steps in CI
=> build xdp using onebranch steps in CI

src/onebranch/onebranch.vcxproj, src/xdpinstaller/product.wxs, src/xdpinstaller/xdpinstaller.vcxproj, src/xdpinstaller/xdpinstaller.wixproj
=> sign xdp installer powershell script

src/xdp.cpp.kernel.props, src/xdp.props
I noticed a few extraneous and broken things while working on other changes to .props files.
=> .props: remove a few things, add a few things

src/xdpinstaller/product.wxs
=> include symbols with msi

.github/workflows/ci.yml, tools/functional.ps1, tools/prepare-machine.ps1, tools/setup.ps1
=> remove unused ebpfjit flag

.github/workflows/ci.yml, tools/merge-artifacts.ps1
=> fix downlevel test execution

src/xdplwf/recv.c
Resolves #630 
Also ensures we do not assume the NIC's RSC headers are naturally aligned.
=> align L3+ headers for RSC segmentation

tools/xdptrace.wprp
These are based on https://learn.microsoft.com/en-us/windows-hardware/test/wpt/recording-pmu-events and https://perfmon-events.intel.com/skylake.html. So far the results are not overwhelming.
=> add some hardware counter profiles

docs/internal/ci-agents.md, docs/internal/readme.md
Migrate managed pool documentation from internal OneNote to GitHub.
=> Add managed pool documentation

test/functional/lib/tests.cpp
Fix powershell escaping.
Do not require higher API versions fail.
CI
No.
No.
=> downlevel test fixes

src/xdpapi/xdpapi.c
The version 2 API wasn't actually being returned.
CI.
No.
No.
=> return API version 2 table for version 2

tools/two-machine-perf.ps1
A refactor broke the netperf script, which we don't currently use.
No.
No.
No.
=> fix typo in netperf script

published/external/afxdp.h, published/external/xdpapi.h, src/xdp/apikernel.c, src/xdp/dispatch.h, src/xdp/offload.c, src/xdp/offload.h, src/xdp/program.c, src/xdp/program.h, src/xdp/xsk.c, src/xdp/xsk.h, test/xskbench/xskbench.c
Close/Delete API to be XdpCloseHandle
=> Unified close handle api

.github/workflows/ci.yml, published/external/xdp/details/afxdp.h, published/external/xdp/details/ioctlfn.h, published/external/xdp/ndis6poll.h, published/external/xdp/wincommon.h, samples/xskfwd/xskfwd.c, samples/xskfwd/xskfwdkm.vcxproj, src/xdp/xsk.c, test/build_headers/ddk/c/ddkheaders.c, test/build_headers/ddk/cpp/ddkheaders.cpp, test/fakendis/inc/fndisnpi.h, test/xdpmp/precomp.h, test/xdpmp/xdpmp.vcxproj, tools/check-drivers.ps1, tools/setup.ps1, tools/xskfwdkm.ps1, xdp.sln
Adds a kernel mode sample of the new XDP kernel mode API and fixes bugs uncovered.
A sanity test is added to the CI using the xskfwdkm sample code.
No.
No.
=> Build XskFwd sample for kernel and user mode

docs/api/XDP_MATCH_PATTERN.md, docs/api/XDP_MATCH_TYPE.md, published/external/xdp/program.h, src/xdp/program.c, src/xdp/programinspect.c, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/taef/tests.cpp, test/spinxsk/spinxsk.c
Add `XDP_MATCH_IP_NEXT_HEADER` match type, documentation, and tests. Resolves #748 
New test case added.
Yes, added.
No.
=> Add built-in filter rule condition XDP_MATCH_IP_NEXT_HEADER

src/xdp.props
We forked release/1.1, so it's time to move `main` to 1.2.
No.
No.
No.
=> bump to version 1.2.0

.github/workflows/ci.yml, docs/release.md
We've forked a new release, so perform some housekeeping.
This adds downlevel tests for 1.1.0 to our CI.
Yes, added.
No.
=> Release housekeeping for version 1.1.0

tools/setup.ps1
After a bugcheck during test development, it is fairly common for the MSI package to be in a logically uninstalled state, but for its components to still be installed on the system. This currently requires manual steps, which is time-consuming and error-prone.
This PR attempts to automate cleanup of this common test failure mode.
Verified locally after inducing a bugcheck during tests.
No, this is all automatic.
No.
=> make uninstall more resilient to bugchecks

.github/workflows/ci.yml
Enable developers to run the CI manually, without creating a pull request.
CI.
No.
No.
=> allow CI workflow to be manually triggered

.github/workflows/ci.yml, tools/rxfilterperf.ps1
Add a microbenchmark for XDP inspection, without AF_XDP sockets.
Ran locally. CI.
No.
No.
=> add rxfilter perf test to CI

docs/release.md
Resolves #557 
No.
Yes, done.
No.
=> finalize xdp 1.1 release

published/external/xdp/details/afxdp.h
Cherry-pick #799 to release/1.1.
=> Fix afxdp.h Struct Initialization (#799)

src/nuget/xdp-for-windows.nuspec.in, src/xdpruntime/xdp-for-windows-runtime.nuspec.in, src/xdpruntime/xdpruntime.vcxproj, tools/setup.ps1
Progress towards #761 - Change NuGet package IDs to Microsoft.* prefix and other tweaks.
CI.
No.
No.
=> Change NuGet package IDs to Microsoft.* prefix

src/xdp.props, src/xdp/program.c, tools/common.ps1, tools/prepare-machine.ps1
Consumes ebpf v0.21.0, including a change in the bpf_program_data structure to consume the breaking change in ebpf.
CICD
n/a
n/a
=> Consume ebpf v0.21.0

Directory.Packages.props, src/xdp.props, src/xdpinstaller/xdpinstaller.wixproj
Use https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management. Ported from an auto-generated internal PR.
CI.
No.
No.
=> Use central package management for nuget

docs/architecture.md, readme.md
Add an architecture document, mostly generated by GitHub Copilot.
Seems to compute :)
Yep.
Nope.
=> add architecture document

.github/workflows/ci.yml, src/xdp.props
Update WDK in release/1.1
CI
No
No
=> Update WDK + CI in release/1.1

src/xdp.props
Increment the patch version number
No
No
No
=> Create patch 1.1.1
