test/xdpmp/rx.c
Fix #59 by moving the RX stats increment into the NDIS helper.
=> Fix XDPMP receive stats

samples/rxfilter/rxfilter.c, samples/rxfilter/rxfilter.vcxproj, src/rtl/inc/xdprtl.h, test/build_headers/sdk/c/csdkheaders.vcxproj, test/build_headers/sdk/cpp/cppsdkheaders.vcxproj, test/common/inc/xdpndisuser.h, test/common/lib/util/util.cpp, test/common/lib/util/util.vcxproj, test/functional/lib/tests.cpp, test/functional/lib/xdptests.vcxproj, test/functional/lwf/lib/ioctl.c, test/functional/lwf/lib/ioctl.h, test/functional/lwf/lib/xdpfnlwfapi.c, test/functional/lwf/lib/xdpfnlwfapi.vcxproj, test/functional/mp/lib/ioctl.c, test/functional/mp/lib/ioctl.h, test/functional/mp/lib/xdpfnmpapi.c, test/functional/mp/lib/xdpfnmpapi.vcxproj, test/functional/taef/tests.cpp, test/functional/taef/xdpfunctionaltests.vcxproj, test/pktcmd/pktcmd.vcxproj, test/pkthlp/um/pkthlp_um.vcxproj, test/rssconfig/rssconfig.c, test/rssconfig/rssconfig.vcxproj, test/spinxsk/spinxsk.c, test/spinxsk/spinxsk.vcxproj, test/xskbench/xskbench.c, test/xskbench/xskbench.vcxproj
Add support for building via the EWDK (a standalone ISO) instead of a locally installed Visual Studio + WDK. Convert all the user mode projects to use the `WindowsApplicationForDrivers10.0` toolset instead of `v142`, which raises the warning level of the projects and requires a few other minor changes.
Resolves #68
=> Support building with EWDK 2022

src/xdp/rx.c
This week, two local stress machines hit a bugcheck where the RX queue's virtual address extension had not been initialized while the data path had become active, even though the data path is dependent on the virtual address extension. Ensure the RX queue is fully initialized before attaching to the interface, which activates the data path.
Should resolve #69 as no other stress bugchecks were hit.
=> Ensure RX queue is fully initialized before attaching to interface

src/xdp/dispatch.c
Remove unnecessary (and misleading) setting of output status parameter when fast IO returns false.
=> code cleanup: don't set output parameters when fast IO fails

published/external/afxdp.h, src/xdp/xsk.c, test/common/inc/xdptest.h, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/taef/tests.cpp
This reverts commit 916a20000c0056e527b82f04c829e9994bde7145 (PR #64) which introduced cancellation of synchronous waits.
With the addition of asynchronous XSK waits, the synchronous wait cancellation is redundant. It also turned out to be insufficient for QUIC's use case.
=> Revert "Add XSK_NOTIFY_FLAG_CANCEL_WAIT Support (#64)"

published/external/xdp/ndis6poll.h
A partner noticed we're using the wrong NDIS handle type, so fix that.
=> Use NDIS_POLL_HANDLE consistently

.github/workflows/ci.yml
Reverts microsoft/xdp-for-windows#83 due to build break in main. The issue is the same as https://github.com/microsoft/action-publish-symbols/issues/27.
=> Revert "Bump microsoft/action-publish-symbols from c82a258c03d72d371fe9138fc887c2c6e1778e38 to 3"

tools/setup.ps1
Resolve #94 
The NDIS polling configuration cmdlet was introduced in WS2022, but we currently don't use NDIS polling on WS2022 due to known issues in its implementation. We are continuing to use NDIS polling uplevel, but design changes to polling have (at least temporarily) broken the NDIS polling configuration cmdlet. Skip setting the configuration to unblock tests.
=> Skip setting NDIS polling configuration

published/external/afxdp.h, published/external/xdpapi.h, src/rtl/inc/xdpassert.h, src/xdpapi/xdpapi.c, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/taef/tests.cpp
Add an optional dispatch table and optional run time linking. Apps can continue to use plain load-time linking for the time being.
A followup PR will convert the remaining test and sample code within the project to use the new versioned APIs.
=> Add minimal XDP user mode API versioning

published/external/afxdp.h, published/external/xdpapi.h, samples/rxfilter/rxfilter.c, src/xdpapi/afxdp.c, src/xdpapi/xdpapi.c, test/functional/lib/tests.cpp, test/rssconfig/rssconfig.c, test/spinxsk/spinxsk.c, test/xskbench/xskbench.c
Consume the new `XDP_API_TABLE` throughout the XDP project and remove support for load-time linkage of XDP routines.
Partially implements #52
=> Consume new API table and remove support for load-time linkage

published/private/xdpif.h, src/xdp/bind.c, src/xdplwf/bind.c
Fix the only known bugcheck in XDP, which can be hit when an interface file object is being created while the underlying LWF interface is being removed. There is currently no protection of the interface underlying an XDP_INTERFACE_SET, so add that protection, which ensures LWF interfaces remain valid until all interface file objects are closed.
This reference protection is implicitly part of the current offload design; its implementation was simply missed. Other design options are possible, which may ease the implementation of interface offload providers and allow them to unload while file objects linger, but for now, just make the point fix within the existing design.
Resolves issue #97.
=> Fix use-after-free bugcheck in offload creation path

test/functional/lwf/sys/tx.c, test/functional/mp/sys/generic/rx.c
STATUS_DEVICE_NOT_READY is both more accurate and results in a more intuitive Win32 error (ERROR_NOT_READY) when the functional test miniport/lwf datapath is paused. The existing error leads to ERROR_ACCESS_DENIED which is not very helpful.
=> Return DEVICE_NOT_READY instead of DELETE_PENDING when NDIS is paused

samples/rxfilter/rxfilter.vcxproj, src/xdpapi/xdpapi.vcxproj, src/xdpetw/xdpetw.vcxproj, test/build_headers/sdk/c/csdkheaders.vcxproj, test/build_headers/sdk/cpp/cppsdkheaders.vcxproj, test/common/lib/util/util.vcxproj, test/functional/lib/xdptests.vcxproj, test/functional/lwf/lib/xdpfnlwfapi.vcxproj, test/functional/mp/lib/xdpfnmpapi.vcxproj, test/functional/taef/xdpfunctionaltests.vcxproj, test/pktcmd/pktcmd.vcxproj, test/pkthlp/um/pkthlp_um.vcxproj, test/rssconfig/rssconfig.vcxproj, test/spinxsk/spinxsk.vcxproj, test/xskbench/xskbench.vcxproj
Several projects in this repository do not have a specified target version, which prevents Visual Studio 2022 from building them.
=> Add missing target version in vcxproj files

src/xdplwf/offload.c
If an LWF injects an OID_GEN_RECEIVE_SCALE_PARAMETERS before any protocol (i.e. open) submits the same OID, then NDIS bugchecks while attempting to cache the RSS parameters on the miniport in a lazily-allocated cache buffer. The cache buffer is allocated by an NDIS routine that isn't called for LWFs.
Prevent this from happening by rejecting XDP set RSS requests until the protocol (e.g. TCPIP) has sent down an RSS OID.
=> Mitigate NDIS bugcheck when RSS is set by a LWF before TCPIP

.github/workflows/ci.yml
The VMs used by GitHub Actions have only two vCPUs, and since the data path is designed to consume _nearly_ all available CPU time, the traces show very long periods without any user mode spinning due to the higher priority data path running on both CPUs.
Adjust spinxsk to use only 1 data path CPU to ensure the other CPU is free for the various spinning threads.
=> Use only 1 queue for spinxsk in GitHub Actions

src/xdplwf/generic.c, src/xdplwf/recv.c, src/xdplwf/recv.h
The NDIS routines that allocate and free NBLs are not very efficient for our use case: most importantly they do not support batching, and they are also just complex.
Instead, use a per-RX-queue list (which can pop a single NBL without any synchronization) and a per-RX-queue s-list (which can push/pop a batch of NBLs in a single interlocked operation) to minimize forwarding overhead.
Increases XDPMP throughput to 350Gbps from 230Gbps on a 4-CPU test machine with 1514-byte frames.
=> Maintain a pool of RX->TX NBLs instead of using NDIS

.azure/azure-pipelines.ci.yml, .azure/templates/build.yml, .azure/templates/devkit.yml, .github/workflows/ci.yml, docs/development.md
Until now, our automation has been building XDP using the Windows Server 2019 agents available in Azure Pipelines and GitHub. 
Since the ebpf-for-windows project is using newer tools, and some of them are mutually exclusive with older versions, upgrade our automation to the same versions as the eBPF project.
Since some IHVs are still using older toolchains (e.g. the 2022 WDK on top of VS2019) create a downlevel build to validate that workflow.
=> Converge on build tools with ebpf-for-windows

published/external/xdpapi.h, src/xdp/program.c, src/xdp/program.h, src/xdp/redirect.c, src/xdp/redirect.h, src/xdp/rx.c, src/xdp/rx.h, src/xdp/xsk.c, src/xdp/xsk.h, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/taef/tests.cpp, test/spinxsk/spinxsk.c
With this change, when a program is plumbed to all queues, it queries the number of HW queues the underlying interface supports and binds the program to all of them including unused ones.
When redirecting packets, check whether the XSK is bound to the queue that is attempting to redirect to it. If not, drop the packets.
=> Add minimal support for binding a program to all RX queues

tools/xdpmpratesim.ps1
It's currently unwieldy to allow XDPMP to run at full speed, so add a simple switch to the rate sim script.
Also set the default adapter name.
Before:
```.\tools\xdpmpratesim.ps1 -AdapterName XDPMP -RxFramesPerInterval "0xFFFFFFFF" -TxFramesPerInterval "0xFFFFFFFF"```
After:
```.\tools\xdpmpratesim.ps1 -Unlimited```
=> Add -Unlimited switch to xdpmpratesim.ps1

tools/rxfilter.ps1
This script helps invoke the `rxfilter` sample program in a more user-friendly way, including scaling across queues.
=> Add rxfilter helper script

tools/xdpmpratesim.ps1
xdpmpratesim.ps1 specifies a default AdapterName, but the parameter is mandatory, which is not useful. Fix that.
=> Fix bug with xdpmpratesim.ps1 requiring a default AdapterName

src/xdp/program.c
The interface offload handle opened in XdpProgramAttach is leaked in the failure path. See issue #151.
=> Fix leaked interface offload handle

test/xdpmp/miniport.c, test/xdpmp/miniport.h, test/xdpmp/rss.c, test/xdpmp/rx.c, test/xdpmp/rx.h, test/xdpmp/tx.c, test/xdpmp/tx.h
Add support for XDP_RX_ACTION_TX to XDPMP, which unblocks testing of _all_ eBPF programs via a native XDP driver.
Without support for XDP_RX_ACTION_TX or currently unobtainable static verifier analysis of the eBPF program, we don't know if it will return the TX action. Therefore, XDP must assume eBPF will return the TX action and reject any bindings to interfaces that do not support TX yet.
=> XDPMP: add support for XDP_RX_ACTION_TX

src/rtl/inc/xdpassert.h, src/xdp/program.c, src/xdp/xsk.c, src/xdp/xsk.h
I'm hit an assert in local spinxsk testing where an XSK was fully disconnected while the RX queue was in bypass mode. This is a legitimate scenario, so relax the constraints to allow disconnected XSKs on this code path.
Also, ensure asserts in CI/CD on debug builds cause the machine to bugcheck - apparently Windows may absorb assertions depending on the system config.
=> Relax assert for detached XSKs in RX bypass

published/external/xdp/program.h, src/xdp/program.c, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/taef/tests.cpp
Added `XDP_MATCH_TCP_QUIC_FLOW_SRC_CID` and `XDP_MATCH_TCP_QUIC_FLOW_DST_CID` for QTIP to work in MsQuic.
=> Add TCP rules for CIBIR

published/external/xdp/program.h, src/xdp/program.c, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/taef/tests.cpp
Due to the issue described in https://github.com/microsoft/msquic/pull/3462#issuecomment-1442727739, we need an extra rule to redirect packets with TCP controls (SYN/FIN/RST). I originally came up with the idea where the new rule should capture packets with actual payload but dealing with control flags is even simpler than checking IP payload length which has to done for both v4 and v6.
=> Add TCP control rule

docs/usage.md, tools/prepare-machine.ps1, xdp.cpp.user.props
Dynamically link to the UCRT provided by the OS for both debug and release builds.
The short term motivation is to enable the `errno` macro/variable shared across binary boundaries between eBPF and our tests. This also gives us slightly smaller binaries, servicing by Windows, etc.
=> Use dynamic linkage to UCRT runtime

src/xdp/program.c
During the refactoring of the program module to support binding to all queues, we lost tracing of XDP program contents throughout the module. To make it simpler to debug the intended and actual programs being loaded by XDP, ensure we trace each time a program is captured, captured programs are compiled into a per-queue program, and programs are attached to queues.
=> Improve tracing of XDP programs

src/xdp/program.c
IPv4 header is not always 20 bytes, as it can contain options (i.e. when HeaderLength > 5)
=> program: discard IPv4 packets with options

src/rtl/inc/xdprtl.h, src/xdp/program.c, src/xdp/xsk.c, test/common/lib/bounce/bounce.c, test/common/lib/bounce/bounce.vcxproj
Use volatile accessors for IO reads to avoid TOCTOU (i.e. double fetches) from user mode.
Resolves #179
=> Use volatile accessors for reads from user mode

src/xdplwf/send.c
Generic XDP omits `MmPrepareMdlForReuse` since the partial MDLs it builds and provides to NDIS are based on MDLs that should already be mapped. However, we do not assert that we don't leak resources or provide any clues on the cleanup path, so do that here.
=> Assert MDL reuse correctness in generic XDP

tools/spinxsk.ps1, tools/xdptrace.wprp
To capture eBPF logs without producing monstrous files or losing the traces when the kernel crashes, enable a 1GB in-memory circular buffer for eBPF logging in spinxsk.
#201
=> Enable 1GB in-memory circular buffer for eBPF logging in spinxsk

src/xdplwf/ec.c
A spinxsk watchdog failure with eBPF is being caused by the EC passive worker sitting in READY state while the data path is running. Ensure the EC passive worker gets to run at high priority during cleanup rundown.
=> Ensure EC passive worker gets boosted during cleanup

published/external/xdp/rtl.h, published/external/xdpapi.h, published/private/xdpif.h, src/xdp/bind.c, src/xdp/bind.h, src/xdp/offload.c, src/xdpapi/xdpapi.c, src/xdplwf/bind.c, src/xdplwf/native.c, src/xdplwf/offload.c, src/xdplwf/oid.c, src/xdplwf/oid.h, src/xdplwf/precomp.h, src/xdplwf/rss.c, test/common/inc/xdpndisuser.h, test/common/lib/util/util.cpp, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/lib/xdptests.vcxproj, test/functional/mp/sys/oid.c, test/functional/taef/tests.cpp, test/spinxsk/spinxsk.c
- Add plumbing for direct OID injection to XDP LWF
- Implement XDP offload API for QEO and pass to the LWF, which passes it to NDIS
- Add minimal implementation of the QEO offload API to the functional miniport
- Add minimal functional and stress test coverage
- Fix a few minor bugs
This does not address #213 or the other nontrivial offload bugs or design issues.
=> Add bare minimum QEO offload support

.azure/templates/devkit.yml, .github/workflows/ci.yml, tools/build.ps1, tools/create-devkit.ps1, tools/create-runtime-kit.ps1
Some of our scripts take a `-Flavor` parameter and others use `-Config`. Use one term.
Resolves #145
=> Use consistent -Config parameter across scripts

src/xdplwf/bind.c, src/xdplwf/filter.h, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/taef/tests.cpp
As part of the prep work for implementing QEO offload cleanup, ensure our offload cleanup within the LWF module occurs before NDIS tears down various control paths.
=> Ensure offloads are cleaned up during detach

test/common/inc/testframeworkapi.h
After much litmus testing, it turns out that the `StopTest` function in the TAEF module is defined as `extern C` in the shared test framework header, which somehow allows exceptions to propagate across module boundaries, prevents exception-handling cleanup from occurring, but allows exceptions to be caught. The exact mechanics of this problem are beyond my understanding, but the fix to make RAII work as expected is simple: do not declare C++ functions as `extern C` within our functional test code.
=> Ensure functional test RAII cleanup occurs

tools/functional.ps1, tools/spinxsk.ps1
A few folks on the eBPF team attempting to locally reproduce test failures have hit issues with XDP attempting to install its own version of eBPF. Add an optional `-EbpfPreinstalled` switch to allow XDP to use the existing eBPF installation.
=> Enable functional and spinxsk tests to run with eBPF preinstalled

src/xdplwf/offload.c
Resolves #225 
It turns out our functional tests were not failing due to a race condition in the tests, but a subtle deadlock introduced in the driver: the `DriverUnload` completes successfully, but a work item deadlocks, which prevents unloading the `xdp.sys` image. Remove the deadlock.
=> Fix deadlock in LWF unload

test/xdpmp/inf/xdpmp.inx, test/xdpmp/miniport.c, test/xdpmp/miniport.h, test/xdpmp/rx.c
In some scenarios, the upper layer protocol will rewrite packet contents. We don't want XDPMP to needlessly memcpy data on each packet, so add a conditional flag that reinitializes the packet data before each RX.
=> XDPMP: conditionally re-copy the pattern buffer into each RX packet

docs/usage.md
The instructions for uninstalling XDP driver do not work for downlevel OSes (Server 2019). Update the instructions to make them work for all OS versions.
=> Update uninstall instructions

.azure/azure-pipelines.ci.yml, .azure/azure-pipelines.longhaul.yml, .azure/templates/spinxsk.yml, .github/workflows/ci.yml
Now that eBPF stress tests are quite reliable, simplify our test matrix and always enable eBPF.
This still leaves eBPF disabled by default in XDP.
=> Always test eBPF in spinxsk CI

tools/setup.ps1
If the job fails to complete in time, we throw an exception and leak the job because we didn't force deletion. Force deletion and continue with regular (non-exception) error handling.
=> Force eBPF powershell job cleanup

src/xdplwf/ec.c
Ensure Ec->OwningProcessor is consistent with Ec->Dpc target processor. In the long haul spinxsk dump, the same EC was running on two processors: inline on CPU 0 and in the DPC on CPU 2. This could happen if the EC ran inline after initialization where the DPC is affinitized to a processor other than the "owning" processor. Ensure these are all consistently initialized.
=> Fix the only AzWatson bugcheck in the last 7 days

.github/workflows/ci.yml
Now that we're using 4-CPU VMs in GitHub actions, we can use the default spinxsk queue count. Also fix up some YAML syntax.
=> Use default spinxsk queue count

.github/workflows/ci.yml, tools/xdpmpratesim.ps1, tools/xskperfsuite.ps1
=> dust off the XSK perf tests and run them in CI

tools/xskperfsuite.ps1
Make an initial cut to the size of the perf test matrix, which is too long.
#256
=> cut perf matrix in half

tools/functional.ps1
In `main` our functional tests run several iterations; we should continue running all iterations even if one iteration fails.
=> continue functional tests upon error

test/functional/lib/tests.cpp
I forgot to advance the RX completion ring, so we re-retrieve the same frame over and over again until either the test case times out or we receive two (!) frames, which causes an assert failure. Advance past the TCP frames we reject.
=> Fix incomplete TCP test case fix

src/xdplwf/rss.c
I've verified NDIS performs the required serialization across OIDs on our behalf, so remove the TODO.
Resolves #56
=> Remove TODO in RSS initialization query

.github/workflows/ci.yml
Similar to our Azure Pipelines CI, build XDP using Visual Studio 2019 to ensure third party devs on VS2019 can use our headers.
=> Add downlevel VS2019 build

.github/workflows/ci.yml, tools/prepare-machine.ps1, tools/upload-perfdata.ps1, tools/xskperfcompare.ps1, tools/xskperfsuite.ps1
Upload perf data to an Azure append storage blob. Azure takes care of appending concurrent blocks on our behalf. The results are publicly available.
=> Upload perf data

.azure/templates/spinxsk.yml, .azure/templates/tests.yml, .github/workflows/ci.yml, tools/prepare-machine.ps1
Add new perf test profile to avoid needlessly installing and uninstalling Azure modules, which is pretty slow. Same with the C++ test framework.
=> Add new -ForPerfTest profile to prepare-machine.ps1

chart.js
Currently all the data lines are gray, so you have to hover to see which data series each line is for. Adding unique colors enables you to ID the datasets without hovering, and also makes it significantly easier to compare the same testcase across variations.
=> Colors for perf chart lines for easier ID

.azure/azure-pipelines.ci.yml
The MsQuic pool only runs spinxsk for 2 minutes, which because of the small sample size of spins, there is a higher chance of outliers. Reduce the minimum success rate to 10% from 50%.
=> Reduce spinxsk success threshold for MsQuic pool

.azure/templates/spinxsk.yml, .azure/templates/tests.yml
MsQuic machines are borked because jobs got cancelled while eBPF was installed, and the check-drivers script runs before the eBPF installer gets downloaded.
Download the MSI installer (and other stuff) prior to checking for lingering drivers.
=> Check drivers after prepare-machine

.azure/templates/tests.yml, .github/workflows/ci.yml, tools/setup.ps1
Fall back to capturing live dumps when eBPF fails to uninstall. I recall there was a problem with something else in the pipeline stalling before the dumps could be uploaded, so also timebox the log conversion step.
#306
=> eBPF uninstall bugchecks aren't being captured, so try again with live dumps

.github/workflows/ci.yml
The test runtime has been commented out - it looks like there was some issue before. Let's see if we can get it working.
=> Limit test runtime in GH Actions

.azure/templates/build.yml, src/xdpinstaller/xdpinstaller.wixproj, tools/common.ps1, tools/setup.ps1, tools/sign.ps1
Install and uninstall XDP using the MSI installer in CI tests. For now, leave the old install/uninstall steps in case we need them.
#307
=> Use XDP MSI in CI tests

src/rtl/xdpregistry.c, src/rtl/xdptimer.c, src/rtl/xdpworkqueue.c, src/xdplwf/oid.c
Add diagnostics for #278: XDP sometimes fails to start in functional tests, even though DriverUnload has exited after the previous stop. It's possible that our IO work items are still referencing the driver, which might explain why the new driver can't be loaded yet.
Add logs to catch XDP in the act, if that's indeed what is happening.
=> Add IO work item logging

tools/setup.ps1, tools/xskperf.ps1, tools/xskperfsuite.ps1
The MSI was failing to install in perf runs because the log directory doesn't exist at the time XDP is installed, so fix that.
Fix the silent failure by making the perf tests stop upon errors.
=> Fix perf runs with MSI

.azure/templates/spinxsk.yml, tools/setup.ps1
We _still_ can't retrieve a dump from the CI when eBPF fails to uninstall: full bugchecks have failed to upload to AzWatson, and our  live dumps fail to upload because PowerShell hangs forever after the MSI breaks.
Try to unblock Powershell and fix a missing timeout in Azure jobs.
=> Improve eBPF uninstall diagnostics

.azure/scripts/agent-functionaltest/Setup.ps1, .azure/scripts/agent-spinxsktest/Setup.ps1
We're seeing less crash dumps uploaded to AzWatson lately; the only change I can think of on our side is collecting much larger complete dumps (on behalf of eBPF) rather than kernel-only dumps.
Sacrifice full info for eBPF in exchange for some idea of what is going wrong in the kernel.
=> Use regular, kernel-only crash dumps in CI

src/rtl/inc/xdprtl.h, src/rtl/precomp.h, src/rtl/xdprtl.c, src/rtl/xdptimer.c, src/rtl/xdpworkqueue.c, src/xdp/dispatch.c
Attempt to mitigate an issue seen during an XDP restart test: XDP's DriverUnload has returned while some IO work items are still being processed on other threads. This is an entirely legal scenario (this is why an IO work item takes a driver object as a parameter: to ensure the driver image stays loaded as long as the work items are running) but the user experience will be best if we close the inevitable unload/worker race condition to as small a window as possible.
On that front, wait for all IO work items in the RTL to run to completion before returning from DriverUnload. This does not guarantee the caller of the work item callbacks (i.e. the kernel / IO manager) has dereferenced the driver object at the time we return from DriverUnload, but it's the best we can do.
Resolves #278
=> Wait for work items before unloading XDP

tools/create-devkit.ps1, tools/create-runtime-kit.ps1
Now that the installer has been tested in CI and manually for a little while and seems robust, provide it in the kits.
=> Provide MSI in kits instead of raw binaries

.github/workflows/ci.yml
Create a dummy job that depends on all other jobs, so our GitHub branch policies can simply require the dummy final job runs successfully.
=> Actions: require all actions succeed

test/functional/mp/sys/oid.c, test/xdpmp/miniport.c
NDIS implements this on our behalf, and we're returning the wrong answer anyways.
=> Remove OID_GEN_DRIVER_VERSION from test miniports

tools/setup.ps1
We're seeing occasional failures in spinxsk where XDP simply fails to start. Since we're only trying 10 times and various fault injections are enabled, try restarting more aggressively to rule out intentional failures to start.
=> CI: try to start XDP 10x more times

published/external/xdp/ndis6poll.h, test/fakendis/inc/fndispoll.h, test/xdpmp/rss.c
As I've been passing through all our headers migrating documentation to markdown, I noticed the NDIS helpers are using a stale data type. Fix that.
=> Use consistent argument types in NDIS request poll helper

.azure/templates/devkit.yml, .github/workflows/ci.yml, tools/create-test-archive.ps1, tools/functional.ps1
Create an archive of tests we intend to use to test backwards compatibility of newer binaries.
Also allow the functional test script to use an alternate test binary. No tests are onboarded to the CI yet since we don't have any backwards compatible releases yet.
Resolves #341
=> Create downlevel test archive

src/xdpinstaller/Product.wxs
The MSI is missing xdpcfg.exe, which should be installed with XDP to allow custom ACL configuration.
=> Add xdpcfg.exe to MSI

.github/workflows/ci.yml
I noticed our new release artifacts zip is missing the devkit and runtime kit, so fix the typo.
=> Fix devkit creation

src/xdp.props, tools/build.ps1, tools/common.ps1, tools/create-devkit.ps1, tools/create-runtime-kit.ps1, tools/create-test-archive.ps1
Attempting to build v0.17.0 from a git tag resulted in a number of errors in AZP. Fix the cascade of errors and revert main's version number to v0.17.0.
=> Fix creation of release artifacts and revert version number

tools/create-devkit.ps1, tools/create-runtime-kit.ps1, tools/create-test-archive.ps1
We're creating dev kits, but the version numbers are only the first digit :(
Use the complete version numbers.
=> Fix kit version numbering

.azure/templates/create-release-artifacts.yml, .github/workflows/ci.yml, src/xdpinstaller/xdpinstaller.wixproj, tools/build.ps1, tools/common.ps1, tools/create-devkit.ps1, tools/create-runtime-kit.ps1, tools/create-test-archive.ps1, tools/setup.ps1
I noticed we're building a runtime kit, which is now obsolete, so remove that.
We're also not stamping the version number onto the MSI, so fix that.
=> Stamp the XDP version number onto the MSI file name

published/external/xdp/datapath.h, src/xdp.cpp.props, src/xdp/programinspect.h, src/xdpcfg/xdpcfg.c, test/pktfuzz/pktfuzz.c, test/pktfuzz/stubs/program.c
Somehow our build isn't configured to use level 4 and treat warnings as errors globally, so fix that.
=> Use warning level 4 by default

.github/workflows/ci.yml, tools/setup.ps1
We expect tests to run on machines without the full git repo checked out locally; the only dependencies are the `tools` directory and the build artifacts. This removes the accidental dependency on `src/xdp/xdp.props` and configures GitHub to check out only the test subdirectory when cloning the repo. Azure Pipelines does not have a similar option AFAICT.
=> Fix and verify test execution outside of CI

.github/workflows/ci.yml
We archive functional tests with each official release; for subsequent releases, ensure the downlevel functional tests pass on the latest build.
=> Add downlevel tests to CI

.github/workflows/ci.yml
Secrets are not shared with PRs from external forks, so we need to skip the runs that require them.
=> Skip Perf When No Secrets are Available

test/common/lib/fnio/filter.c
When a TX NB containing multiple MDLs is filtered, we would expect the resulting frame to either
1) Contain a single data buffer with all bytes of all MDLs or
2) Contain a data buffer per MDL
In the case of a 2-MDL NB where the first MDL's ByteCount > NB data length, we end up with a single data buffer containing just the bytes of the first MDL.
Fix this so that we consistently end up with option 2 above.
=> Fix fnio filter for multi MDL NB

.github/workflows/ci.yml
We're required to onboard this repo to CodeQL, so invoke the appropriate actions during a weekly scheduled build.
=> Add CodeQL to CI build

test/rssconfig/rssconfig.c
The rssconfig test tool commands leverage 2 (get config, set config) out of the 3 (get config, set config, get capabilities) main experimental RSS APIs. Add a command to leverage the third. This new command is helpful to see which adapters support RSS instead of guessing or using other methods outside of rssconfig.
Also fix a bug in rssconfig regarding XdpGetRoutine error checking.
=> Add capabilities command to rssconfig

.github/workflows/ci.yml, test/pktfuzz/pktfuzz.vcxproj
The CI and my dev box stopped being able to build and run pktfuzz.exe, so include the ASAN runtime dependency along with the fuzzer binary.
Resolves #412
=> fix / work around pktfuzz ASAN dependency change

.github/workflows/ci.yml
Our ASAN user mode fuzz tests stopped working on WS2019. Disable them since they only need to run on one platform, and WS2022 is still working.
=> Disable fuzz tests on 2019

published/external/xdpapi_experimental.h, src/xdpapi/xdpapi.c, test/rssconfig/rssconfig.c
Resolves the following static analysis issues for a typical app that queries the required length for capabilities/configuration, allocates a buffer of that length, and gets the capabilities/configuration using that buffer.
```
error C6386: Buffer overrun while writing to 'RssCapabilities':  the writable size is 'RssCapabilitiesSize' bytes, but '28' bytes might be written.
error C6386: Buffer overrun while writing to 'RssConfig':  the writable size is 'RssConfigSize' bytes, but '24' bytes might be written.
```
=> Improve SAL for RSS APIs

src/xdp/program.c, src/xdp/xdpp.h, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/taef/tests.cpp, test/spinxsk/spinxsk.c
Fixes #401
This PR:
1. Adds `add_context` and `delete_context` functions for XDP eBPF extension. These functions allow `bpf_prog_test_run` to be used with XDP extension.
2. Adds tests which invokes `bpf_prog_test_run` flow.
=> Add context create/delete functions

tools/prepare-machine.ps1
When running the perf tests on some new machines, certutil seemed to be succeeding but still writing some wierd error output. Ignoring it seems safe, so we are just redirecting the output. The perf run then passed.
=> Redirect Error Output from certutil.exe

.github/workflows/ci.yml
Ensure adding a new downlevel version won't collide with existing artifact paths.
=> Further disambiguate downlevel artifact upload name

src/bpfexport/bpfexport.c, src/bpfexport/bpfexport.rc, src/bpfexport/bpfexport.vcxproj, src/xdp/ebpfstore.h, src/xdp/program.c, src/xdpinstaller/Product.wxs, test/bpf/bpf.vcxproj, tools/create-devkit.ps1, tools/prepare-machine.ps1, tools/setup.ps1, xdp.sln
This fixes #400 by adding a export tool for XDP program information.
=> Bpf export

src/xdp/program.c, src/xdp/program.h, src/xdp/rx.c, test/bpf/bpf.vcxproj, test/bpf/selective_drop.c, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/taef/tests.cpp
Fixes #448 
This PR populates `ingress_ifindex` in `xdp_md` struct passed to the eBPF program. Also added test to validate that ifindex is correctly populated.
=> Populate `ingress_ifindex` in `xdp_md` struct.

published/external/xdpapi.h
This comment should have been removed when XDPAPI v1 was introduced
=> Fix outdated XDPAPI v0 comment

tools/two-machine-perf.ps1
For WS2025 machines you are required to pass the credentials explicitly to be able to connect the remote PowerShell session. This copies the code from MsQuic.
=> Fix WS2025 netperf Test Execution

.github/workflows/ci.yml, docs/release.md, src/xdpinstaller/Product.wxs
1. Make the installer pick up the xdpapi.dll binary from the `xdp` subdirectory, i.e. the driver package, which is less likely to be miscopied by human error than the version of xdpapi.dll in the bin root.
2. Make the 1.0 release link point to the 1.0 tree, not just the 1.0.0 tag.
3. Add 1.0.1 to the downlevel test list.
4. Remind releasers to update the downlevel tests.
=> Minor updates and cleanup for v1.0.1 release

.github/workflows/build.yml, .github/workflows/ci.yml
The refactored build script broke in main: the secret PAT doesn't automatically propagate to the reusable workflow.
=> Fix PAT for publishing symbols

tools/setup.ps1
To attempt to make eBPF uninstall more resilient to various errors, uninstall using `Uninstall-Package` if the local MSI uninstall failed.
=> Uninstall eBPF using Uninstall-Package

.github/workflows/build.yml
For some reason dependabot has not picked up newer changes of the setup-msbuild action. This left us with a stale version which is now causing warnings during the CI build. Manually bump the version to resolve the build warnings and hope dependabot starts working.
=> Update setup-msbuild manually

test/functional/lib/tests.cpp
=> Reference parameter consistency

.azure/azure-pipelines.longhaul.yml
Try to avoid internal flags being raised about machines running for a day: set the runtime target to 22 hours.
=> spinxsk: reduce longhaul stress runtime

src/xdp/programinspect.c, src/xdplwf/recv.c, test/functional/lib/tests.cpp
While testing the new RSC forwarding feature, I discovered two latent bugs in handling fragmented frames.
1. The built-in filtering engine failed to properly handle cases where the fast (contiguous) routine partially validated and cached headers before falling back to the fragment parsing routine. When this happened, the wrong bytes were copied into the contiguous header buffer, leading to incorrect filtering.
2. The generic TX forwarding action allowed packets containing potentially discontiguous headers onto the local RX path, which on older builds of Windows causes bugchecks, and on newer builds causes packet drops. Avoid this by copying the entire packet if such a fragmented packet occurs. This could impact performance because most IPv4 traffic and UDPv6 traffic generated by the TCPIP …
=> Fix two bugs mishandling fragmented frames

src/xdp/programinspect.c, src/xdplwf/recv.c, test/functional/lib/tests.cpp
Cherry-pick #508 onto release/1.0. This backports the test coverage as well as functional fixes. No need to spin up a standalone release for these fixes.
=> release/1.0: fix two bugs mishandling fragmented frames (#508)

src/xdplwf/recv.c
I discovered another latent bug in the RX->TX forwarding path while working on RSC. This one already has sufficient spinxsk test coverage to hit, but we simply had a low rate of crash dumps being successfully uploaded to AzWatson. Eventually I was able to repro locally and fix.
=> prevent MDL use-after-free in generic RX->TX forwarding

tools/two-machine-perf.ps1
The new two-machine perf tests specify `-ErrorAction 'Continue'` for each command within the remote script block, but, curiously, PowerShell treats errors in local and remote script blocks differently. Without digging into why exactly there is such a difference, simply specify each invocation of the remote script block is to have its errors continued.
Avoids situations like the following:
```
====================CLEAN UP====================
Stopping remote logs...
##vso[task.setvariable variable=NeedsReboot]true
Write-Error: C:\actions-runner\_work\netperf\netperf\tools\two-machine-perf.ps1:289
Line |
289 |      Invoke-Command -Session $Session -ScriptBlock {
|      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| wpr.exe failed: …
```
=> perf test: continue past errors during cleanup

published/external/afxdp.h
The latest VS2022 toolchains fail to suppress the nameless struct/union warning in C++ mode. I don't know why that is, but work around it by suppressing it a different way.
=> fix new afxdp.h nameless struct warning

.github/workflows/build.yml, .github/workflows/ci.yml
This is the last remaining usage of the ADO PAT, which has become an increasing maintenance burden.
The symbols are barely used, so just stop publishing them for now.
=> don't publish symbols in github builds

.github/workflows/ci.yml
The netperf workflow has been almost completely unreliable and introducing noise, and we're not using the results, so disable it for now. We still have the 1-machine perf tests in automation.
Resolves #527
=> don't trigger netperf from CI

src/xdp.props, test/functional/lib/tests.cpp, tools/common.ps1
Our functional tests can bugcheck if filtered NBLs are left pending in the FNMP/FNLWF. This happens if the test fails for some reason, causing an exception to be thrown and objects destructed. If the test cases don't have their handles declared extremely carefully, then an object (like an XDP program or XSK handle) might be destructed before the FNMP/FNLWF handle, causing an infinite hang.
Use the new win-net-test API to atomically clear the FNMP/FNLWF filters and return NBLs, and return an RAII object whenever a filter gets set.
Resolves #510 
Also consumes a new bugfix for FNLWF that ensures its data path doesn't pause until all filtered RX frames are returned.
=> clean up pending NBLs in FNMP and FNLWF using RAII

.github/workflows/ci.yml
I just noticed we're not running stress tests on prerelease Windows builds - this seems to be a day-zero bug in our GitHub actions.
=> run stress tests on Windows prerelease

tools/setup.ps1
When Rename-NetAdapter failed, it wasn't hitting the local catch block. Fix that and preserve the final exception.
Resolves #536
=> Fix retry logic during Rename-NetAdapter

test/functional/lib/tests.cpp
Because our tests reuse ports and sequence numbers, it's relatively easy for our tests to be confused by old TCP sockets gracefully closing in the background. Use abortive shutdown by default, causing a single RST to be sent immediately.
Resolves #537
=> Prevent TCP connections lingering beyond intended lifetime

tools/spinxsk.ps1
The spinxsk tests run for 10 minutes in PRs and 60 minutes in main, and every once in a while we hit a "bad" run where the success rate is less than 1%. Other times the success rate can be as high as 15%.
Try running each iteration for twice as long (10 minutes) to let the randomized test converge to the mean.
Resolves #536
=> Reduce spinxsk variance

tools/spinxsk.ps1
#539 introduced a new problem while trying to solve #536: the PR tests are running a final runt iteration of 1 minute, which is so short it is guaranteed to be noisy. Ignore the success threshold for the final iteration if it is just leftover time.
=> spinxsk: ignore success threshold in final short iteration

.github/workflows/ci.yml, test/pktfuzz/pktfuzz.vcxproj
Port #413 to release/1.0 to close #479.
I still don't understand why fuzzing doesn't work properly on prerelease builds.
=> release/1.0: fix / work around pktfuzz ASAN dependency change (#413)

.github/workflows/ci.yml
Port #532 to release/1.0. Pretty much a total rewrite, but leaving the link as a breadcrumb.
=> don't publish symbols in github builds (#532)

.github/workflows/ci.yml, test/functional/taef/tests.cpp, tools/functional.ps1
Amazingly, vstest.console.exe can't filter arbitrary attributes, and it doesn't seem to be able to pull the "supported" TestCategory attribute, either. I can't believe this is the case (I must be doing something wrong) but work around this apparent restriction by setting the priority of "prerelease" test cases to 1.
Resolves #526
=> don't run prerelease tests downlevel, part 2

.github/workflows/ci.yml
Require all stages actually succeed, not just finish running (or fail, skip, cancel, etc.).
=> Actually require all CI jobs succeed

src/xdp.props, src/xdplwf/oid.c, test/functional/lib/tests.cpp, test/functional/lib/tests.h, test/functional/taef/tests.cpp, tools/common.ps1
Today, if a direct OID gets completed inline, we accidentally call the regular NDIS completion routine. This is a bug, and we should call the appropriate direct OID variant for direct OID requests.
Also add test coverage for OIDs passing through XDP unscathed.
Resolves #498 (I think).
=> Fix direct OID completion

src/xdp/program.c
eBPF extensions must validate the header version. Any change to the header version is a breaking change.
The use of header.size in version ~~1~~ 0 of the extension data is a bug (it should be the size of the extension data _struct_, not the optional data) but XDP must continue relying on this behavior.
=> fix ebpf struct version validation

tools/prepare-machine.ps1
The perf tests no longer depend on Azure storage accounts, and recent CI images stopped supporting the module. Remove the dead code.
=> remove defunct and now broken az storage dependency

.azure/templates/build.yml, .github/workflows/build.yml, src/xdp.cpp.kernel.props, src/xdp.cpp.props, tools/build.ps1, tools/create-devkit.ps1, tools/prepare-machine.ps1, tools/setup.ps1
Progress towards #585
This eliminates the dependency on the corenet test signing certificate and signs binaries using msbuild.
=> sign driver packages within msbuild

tools/build.ps1
Let developers sanity test the xdp-onebranch.sln file on dev builds.
=> build.ps1: optionally build xdp-onebranch.sln

published/private/xdpwdk.h
The build is failing on internal WDKs newer than WS2022.
=> fix macro guard version for NET_BUFFER_LIST_IS_TCP_RSC_SET

src/nuget/xdp-for-windows.nuspec.in
OneBranch doesn't produce xdpnmr.pdb for some reason. We don't strictly require this PDB in our nuget since Native XDP is not officially supported. Our long term plan is to replace the NMR static lib with a header-only library, so the long term path was removal anyways.
=> remove xdpnmr.pdb from nuget

.github/workflows/ci.yml
Thanks to #575, our functional tests take a lot longer. That PR bumped both the PR and main runtimes, but the main runtime should probably be 10x the PR runtime, since we run 10 iterations. The main CI appears to be timing out, and the test timeout might cause the machines to bugcheck, depending on which test happens to be running when the functional test is aborted.
Also bump the log conversion time, since that also seems to be timing out in main.
=> extend main runtime

src/nuget/nuget.vcxproj, src/xdpinstaller/xdpinstaller.wixproj, tools/build.ps1
OneBranch needs to do binary signing outside msbuild before packaging a nuget, so allow the nuget project to be built independently.
=> allow dev nuget to be built in independent build stage

.github/workflows/ci.yml
The 10 minute log convert timeout is flaky in main, so extend it a bit more. If 15 minutes still is not enough, perhaps we should not convert the logs in main.
=> extend log convert timeout CI

src/xdpinstaller/xdpinstaller.vcxproj, src/xdpinstaller/xdpinstaller.wixproj
test sign the MSI with the same cert that signed xdp.sys, so that the MSI's cert can be extracted and installed prior to installing the MSI itself.
```PowerShell
$CertFileName = 'xdp.cer'
Get-AuthenticodeSignature 'xdp.msi' | Select-Object -ExpandProperty SignerCertificate | Export-Certificate -Type CERT -FilePath $CertFileName
Import-Certificate -FilePath $CertFileName -CertStoreLocation 'cert:\localmachine\root'
Import-Certificate -FilePath $CertFileName -CertStoreLocation 'cert:\localmachine\trustedpublisher'
```
=> test sign installer

.github/workflows/ci.yml
I'm seeing some flakiness in the spinxsk test, where general sluggishness (WPR, antivirus scans, etc.) causes the actions timeout to be slightly exceeded. Extend the actions timeout, which is independent of the actual watchdog timeouts under test.
=> extend spinxsk actions timeout

src/xdplwf/send.c
The LWF has a configurable TX frame limit, but we don't supply the value to XDP, which chooses the effective ring size.
=> lwf: provide tx frame count hint

tools/setup.ps1
Progress towards #585 
OneBranch doesn't produce an xdp.cer file, so we need to extract the xdp.cat signing certificate.
=> remove dependency on xdp.cer

.azure/agents/functional.json, .azure/agents/spinxsk.json, tools/prepare-machine.ps1
By default, Windows will delete system crash dumps if the system is low on disk space. This seems to happen pretty often on my local machines, at least, and _might_ be contributing to crash dump loss in CI. Set a config knob that forces the crash dump to be retained.
=> always retain crash dumps

src/xdp.props, src/xdp/packages.config, test/functional/lib/xdptests.vcxproj, test/pktcmd/pktcmd.vcxproj, test/pktfuzz/pktfuzz.vcxproj, test/xdpmp/xdpmp.vcxproj, tools/common.ps1, tools/prepare-machine.ps1
We need to update the test binaries to use the same major version as the uplevel tests.
=> consume win-net-test 1.0.0 in release/1.0

.github/workflows/ci.yml
We're getting warnings and poor CI usability on release/1.0 due to outdated artifacts helpers. We need to find a long term solution to maintaining these release branches, but for now, manually update dependencies.
=> upgrade to latest artifacts tasks

docs/usage.md, src/xdp.cpp.user.props, test/common/lib/util/util.vcxproj, tools/common.ps1, tools/prepare-machine.ps1, tools/setup.ps1
Technically a breaking change. We need to use dynamic linking to VCRT in our internal, official builds for the debug flavor, so we should use it everywhere.
=> switch to dynamic linked VCRT

src/rtl/inc/xdprtl.h, src/xdplwf/offloadtask.c, src/xdplwf/recv.c, test/xskbench/xskbench.c
Make it harder to be an F short or long in a literal by using macros instead.
=> replace 0xFF+ literals with macros

src/onebranch/onebranch.vcxproj, src/xdppcw/xdppcw.vcxproj, src/xdpruntime/xdpruntime.vcxproj
We unintentionally started rebuilding binaries during package stage in #638
=> don't rebuild runtime deps during package stage

tools/publish-nuget.ps1
Make publishing a NuGet package foolproof and Powershell-friendly.
=> add a nuget publishing wrapper script

.github/workflows/ci.yml
Our CI has 2 warnings in GitHub because the fuzz tests do not create logs on pass. Suppress the warning since this is expected behavior.
CI.
N/A.
N/A.
=> clean up warning for no logs uploaded in fuzz tests

src/nuget/xdp-for-windows.nuspec.in, src/nuget/xdp-for-windows.props, src/xdpruntime/xdp-for-windows-runtime.nuspec.in, src/xdpruntime/xdp-setup.ps1, tools/update-nuspec.ps1
Partially solves #674 by moving architecture-specific binaries to architecture-specific directories in nugets. Since x64 is the only arch we currently build for, this does not actually merge multiple architectures into one nuget.
Compiles locally.
This is a breaking change to the file structure of our nuget packages. As of yet, no nuget packages have been included in an official and supported release.
This does not change the MSI, which is architecture-specific.
=> move binaries to arch-specific directories in nugets

tools/functional.ps1
A JIT workaround was made redundant by a previous PR (#584) but failed to clean up a dead variable. Powershell 7 notices this and errors out. Resolves #681 
CI, verified locally.
N/A.
N/A.
=> remove JIT relic

src/xdp.props, src/xdp/packages.config, src/xdpinstaller/product.wxs, src/xdpinstaller/xdpinstaller.vcxproj, src/xdpinstaller/xdpinstaller.wixproj
Upgrade from WiX 3.14 to WiX 5, which includes full support for ARM64. WiX 4 uses a different build project system (.NET SDK) which required a few other changes.
Builds locally.
No. I need to double check that the .NET SDK magically gets installed via the new project system.
No :)
=> upgrade to wix 5

src/xdpinstaller/xdpinstaller.wixproj
WiX 5 no longer has a `Link` target, so the `SignMsi` target is never executed in the MSI project.
Verified locally.
No.
Not really.
=> fix MSI test signing

.azure/onebranch.test.yml, .azure/templates/build.yml, .azure/templates/spinxsk.yml, .azure/templates/tests.yml, .github/workflows/build.yml, .github/workflows/ci.yml, src/nuget/nuget.vcxproj, src/xdpruntime/xdpruntime.vcxproj, tools/build.ps1, tools/check-drivers.ps1, tools/common.ps1, tools/create-test-archive.ps1, tools/functional.ps1, tools/log.ps1, tools/merge-artifacts.ps1, tools/pktfuzz.ps1, tools/rxfilter.ps1, tools/setup.ps1, tools/spinxsk.ps1, tools/two-machine-perf.ps1, tools/update-nuspec.ps1, tools/xskperf.ps1, tools/xskperfsuite.ps1
For some reason lost to the sands of time, we have a mix of "arch", "architecture", and "platform" across scripts and YAML, and all have the same meaning. Use "platform" consistently, because this aligns with the msbuild system.
CI.
No.
No.
=> replace "arch" with "platform"

tools/log.ps1
Our ARM64 VMs do not support sampling profiles, but otherwise should support logging. See if that works.
CI.
Nope.
Nope.
=> enable non-sampling logs on arm64

src/rtl/inc/xdprtl.h, src/xdp.cpp.props, src/xdp/xdp.inx, src/xdp/xdp.vcxproj, src/xdplwf/precomp.h, test/xdpmp/inf/xdpmp.inx
Resolves #652 
Tested locally. Newest WDK is not readily available in CI, though with a nuget package, we could do it.
No, the newest WDK is still not recommended or officially supported for builds by XDP.
No.
=> make xdp build again on latest wdk

published/external/afxdp_helper.h, published/external/xdp/rtl.h, src/xdp/xsk.c
I used the wrong macro to detect arm64, so we were using a full barrier needlessly.
CI
No
No
=> fix arm64 barrier optimization

src/xdpruntime/xdp-for-windows-runtime.nuspec.in, tools/update-nuspec.ps1
Previously, we decided to make our runtime nuget contain binaries for all architectures. This imposes more burden (package size, signing, etc.) than necessary, so split the runtimes back out. Leave the developer nuget as logically merged, because that is much more convenient for everyone.
CI.
No. Runtimes aren't documented yet.
Sorta.
=> recant and make runtime nugets per-architecture

.azure/templates/build.yml, .github/workflows/build.yml, docs/development.md, tools/prepare-machine.ps1
eBPF removed the clang version 11 requirement, so remove XDP's matching requirement. Developers should use the latest clang now.
CI.
Yes.
No.
=> remove clang 11 requirement

test/bpf/bpf.vcxproj
Consume latest undock by transitivity. This moves nuget autogen files into the artifacts/obj directories, as intended.
CI.
No.
No.
=> update cxplat (and undock)

.github/workflows/build.yml, .github/workflows/build_matrix.yml, .github/workflows/ci.yml
#706 only supported PR runs, and broke non-PR runs. Try to fix that so we compare the current `github.ref` to the previous commit for non-PRs. Also, #706 was fundamentally broken: it failed to actually build the base_ref, and instead built ref again.
CI.
No.
No.
=> try to resolve the previous commit in non-PR runs, too

published/external/afxdp_helper.h, src/xdp/xsk.c
The shared user/kernel rings contain fields that are contended between producers and consumers; in some cases, the previously witnessed values are still usable (i.e., would not block progress) and so may be cached into uncontended memory. This improves performance by reducing inter-processor cache coherence overhead.
CI.
No. The improvements are entirely contained within the helper library and XDP runtime.
No.
=> make the xsk shared rings more cache-friendly

.github/workflows/build_matrix.yml, docs/development.md, src/xdplwf/precomp.h, test/functional/lib/tests.cpp, test/pktfuzz/pktfuzz.c
We had added support for building the entire XDP project in VS2019 because some native XDP driver developers were using VS2019 for their existing NIC codebases several years ago. VS2019 has broken our build yet again.
Since the time horizon to VS2025 is presumably shorter than the horizon to native XDP, and because building a third-party XDP driver doesn't actually require building the entire XDP project (it only needs its headers and output libs) stop building VS2019 in automation.
CI.
Updated required VS version.
No.
=> remove support for vs2019 in builds

src/rtl/xdprtl.c, test/xdpmp/hwring.h
From code review, two variables get read without the necessary volatile accessors, potentially leading to undefined behavior.
CI.
No.
No.
=> fix two reads missing volatile NoFence reads in test/dbg code

tools/log.ps1, tools/spinxsk.ps1
We've upgraded our amd64 perf pool to gen6 VMs, which support CPU profiling, so re-enable that profile in our logging script. Our spinxsk pool is in a different region, which doesn't yet have gen6 VMs, so keep profiling disabled there.
CI. Verified ETLs are uploaded for perf runs.
No.
No.
=> Re-enable CPU profiling on arm64

src/xdp/program.c
If a NIC does not support RSS, it will report zero RSS queues. In that case, the program should bind to the implicit 0th queue for all traffic.
Resolves #734 
Regression tests. This is not a generally important XDP scenario for testing, since all medium- and high-performance NICs support RSS.
No.
No.
=> fix XDP_CREATE_PROGRAM_FLAG_ALL_QUEUES when RSS is not supported

samples/xskfwd/xskfwdkm.h, src/xdp/xsk.c
From code review, there are a few places where we assume/assert the IO caller is user mode.
Not yet - adding test coverage and any final fixes in a standalone PR officially adding KM support.
No.
No.
=> fix up a few cases where user mode was assumed

published/external/xdp/details/xdpapi.h, published/external/xdpapi.h, src/xdp/dispatch.c
Add a driver start callback API. This callback will be invoked each time the XDP driver has been started.
CI for callback producer.
This API will remain undocumented.
No.
=> add driver start callback API

tools/common.ps1
Resolves #710 by allowing developers to build the project in detached HEAD state on dev boxes. This now only raises a warning, because official builds depend on deducing the target branch or tag.
Verified locally.
No.
No.
=> Allow xdp to build from detached HEAD state on dev box

src/xdp.props
`WntPackagePath` was defined twice, and the first definition is wrong and unconditionally overridden.
CI.
No.
No.
=> clean up stale global msbuild property

.github/workflows/ci.yml
There have been a few instances of functional tests running beyond the current timeout in `main` tests, so bump the timeout again. In the long run, we need to find a way to speed up the slow tests, e.g., move spin tests into dedicate spin jobs, run tests in parallel.
No.
No.
No.
=> extend functional test runtimes

src/xdpruntime/xdp-setup.ps1
The XDP installer script produces an error when uninstalling an already uninstalled component, which was not by design. Attempt to remove files only if they actually exist.
CI.
No.
No.
=> silently ignore non-existent files

published/external/xdp/ebpfhook.h
struct xdp_md was incorrectly named with xdp_md_.
The ebpf programs use 'struct xdp_md" in the internal project. Hence renaming the struct to the libbpf standard.
_Do any existing tests cover this change? Yes Are new tests needed?No
_Is there any documentation impact for this change? No
_Is there any installer impact for this change? No
=> Rename xdp_md_ to xdp_md

src/xdplwf/send.c, test/functional/lib/tests.cpp
We were already implicitly supporting only no-extension IPv6 for checksum offloads, so formalize this for now. We can add full support for IPv6 extensions in the future if we get a customer ask, which will require more careful validation on behalf of NICs.
Updated.
No.
No.
=> un-support ipv6 extensions with tx offload for now

.github/workflows/ci.yml, test/ringperf/ringperf.c, test/ringperf/ringperf.vcxproj, tools/ringperf.ps1, xdp.sln
We've been trying to understand x64 vs arm64 performance gaps, so establish a microbenchmark focusing on a small amount of code.
Builds and runs locally.
No.
No.
=> add skeleton ring perf microbenchmark

tools/rxfilterperf.ps1
I accidentally used sample + precise profile in the new rxfilter perf test, which introduces a ton of profiling overhead. Switch to the intended profile.
CI.
No.
No.
=> rxfilter: use sample-only cpu profile

.github/workflows/ci.yml, tools/rxfilterperf.ps1
We are testing only the "system" mode by default, which for XDPMP defaults to native mode. Since the LWF mode is what all scenarios currently use, we need to add coverage for that, too.
CI.
No.
No.
=> rxfilterperf: test both LWF and native XDP code paths

readme.md
I noticed we still have a link to a performance dashboard on our GitHub page, but that dashboard's underlying data has been removed. Remove the link to the dashboard for now.
No.
Stale documentation removed.
No.
=> remove dead perf dashboard link

src/rtl/inc/xdprtl.h, src/xdppcw/inc/xdppcw.h
Our stats macros were using plain read/write operations, which could result in torn values. This was somewhat acceptable, but we might as well ensure the operations are atomic.
CI.
No.
No.
=> fix up stats macros to use atomic get/set

.github/actions/perf/action.yml, tools/xskperf.ps1, tools/xskperfsuite.ps1
To determine the performance cost of AF_XDP memcpy, run the tests with both RX and TX copying disabled. This also provides an estimate of the eventual performance of a native zerocopy driver API.
CI.
No.
No.
=> add perf tests without memcpy

src/xdp/rx.c
The `XdppReceiveBatch` routine calls a parameterized inspection routine for each frame in a batch, and the routine is always known at compile time. However, our arm64 builds do not inline this routine, causing an indirect function call at runtime, which is showing up as a hot spot in perf graphs.
Force the compiler to inline this routine and (hopefully) convert the function parameter to a direct call.
CI. Verified arm64 assembly is as expected locally.
No.
No.
=> Force inline XdppReceiveBatch

.github/actions/perf/action.yml, .github/workflows/ci.yml, tools/common.ps1, tools/perfcompare.ps1, tools/prepare-machine.ps1, tools/xskperfsuite.ps1
Instead using of an opaque, fragile, and hard-to-extend CSV file to store performance data, use JSON. The JSON file is an array of perf test cases, with each test case containing an array of metrics, along with other metadata.
Sample output file:
```
[
{
"MachineName":  "WINLATEST",
"Timestamp":  "2025-01-08T16:56:55.6232183-05:00",
"CommitHash":  "",
"Metrics":  [
{
"Scale":  1000,
"Name":  "pps",
"Value":  5140.379
}
],
"ScenarioName":  "XDPMP-GENERIC-RX-BUSY-2048chunksize-64iosize",
"Platform":  "x64",
"OsBuild":  "26330.5002.amd64fre.ge_current_directiof.241117-1100"
},
{
"MachineName":  "WINLATEST",
"Timestamp":  "2025-01-08T16:57:04.2804892-05:00",
"CommitHash":  "",
"Metrics":  [
{
"Scale":  1000,
"Name":  "pps", …
```
=> use JSON instead of CSV for xskperfsuite and perf comparison script

.github/workflows/ci.yml
Our perf tests started timing out in main after I added a zerocopy test. Bump the timeout again.
CI.
No.
No.
=> bump perf test timeout

tools/perfcompare.ps1
When making a breaking change to the perf schema, we had to keep support for the old schema when we compare to build N-1. Now that build N-1 also uses JSON, remove CSV.
CI.
No.
No.
=> remove CSV perf data support

tools/common.ps1, tools/xskperfsuite.ps1
This unblocks #786 by splitting the refactoring of perf data out from the new summary steps. This also ensures arbitrary file paths can be specified for the filename by creating the parent directory, if necessary.
CI.
No.
No.
=> Further refactor perf data creation into common.ps1

src/xdp/xsk.c
The TX bounce buffer is currently allocated without initialization, which is functionally correct and reasonably secure (the contents are not mapped into user space). For defense in depth, consistently use zero'd pool allocations across XDP unless the perf cost is unacceptable.
Some code paths may implicitly use non-initialized memory (e.g. NBLs allocated by NDIS) and are out of scope.
CI.
No.
No.
=> remove uninitialized pool allocation

samples/directory.build.props, src/onebranch/onebranch.vcxproj, src/xdp.props, src/xdpinstaller/xdpinstaller.wixproj, test/directory.build.props
We paused OneBranch builds several months ago, and in the meantime, both XDP and OneBranch made breaking changes. Fix all of those. Resolves #789 
It builds in OneBranch or your money back.
A bit of comments were added.
No.
=> Make XDP build in OneBranch again

.azure/onebranch.test.yml, .azure/templates/build.yml, .azure/templates/spinxsk.yml, .azure/templates/tests.yml, .github/workflows/ci.yml, src/nuget/nuget.vcxproj, src/xdpruntime/xdpruntime.vcxproj, test/functional/lib/tests.cpp, tools/common.ps1, tools/functional.ps1, tools/setup.ps1, tools/spinxsk.ps1
Resolves #794
Adds support for installing XDP with the runtime nuget package in test automation. Uses this new config in GitHub for stress tests (as a sanity test) and in OneBranch tests.
CI.
No.
No.
=> Add NuGet runtime tests

.azure/onebranch.test.yml
Our functional tests have become larger and slower, so bump the newly re-onboarded ADO tests to use the same timeout as GitHub.
CI.
No.
No.
=> fix azure functional test timeout

published/external/xdp/details/afxdp.h
Fixes #797 by modifying the struct initialization logic. Note that this will need to be backported to release/1.1.
CI/CD
N/A
N/A
=> Fix afxdp.h Struct Initialization

.azure/templates/tests.yml
#796 bumped the timeout value, but the ADO job was still using the default 60 minutes. Plumb it properly.
Verified on internal CI.
No.
No.
=> Apply ADO timeout to jobs

src/xdp/xdp.vcxproj
On a clean device, nuget would fail to restore packages because LatestWdkPlatformVersion == ''.
After clearing the nuget cache, a build to restore nuget packages.
N/A
N/A
=> Add empty check to let nugget parse the prop file

docs/usage.md
We added a runtime nuget package, but did not document the steps to use it. Since it is now officially supported, add the missing documentation.
N/A.
N/A.
N/A.
=> add documentation for nuget runtime install steps

src/xdplwf/recv.c
Remove an invalid assertion in XDPLWF for low resource scenario.
The assertion was triggered through a run of SpinXsk with added support for FNMP.
The assertion assumed that it could be reached only when a single NB would be processed by the function.
This is incorrect: in low resource scenario, XDPLWF ensures that a single frame is submitted to XDP for inspection, but it can skip multiple NB (loopback, failure to map the MDL).
When this is the case, the pose-inspection will need to process multiple NB and the assertion can be incorrect if an NB was skipped then another NB was submitted for inspection.
C/I, no logic change.
N/A
N/A
=> Remove invalid assertion in XDPLWF in low resource scenario

test/xskbench/xskbench.c
To help identify potential causes of latency, add optional IO completion watchdogs to xskbench.
Verified locally that these break into KD (when attached) and print statistics to the console.
Added to xskbench help text.
No.
=> add IO completion watchdogs to xskbench

src/nuget/nuget.vcxproj, src/nuget/xdp-for-windows.nuspec.in, src/xdpruntime/xdp-for-windows-runtime.nuspec.in, src/xdpruntime/xdp-for-windows-runtime.props, src/xdpruntime/xdpruntime.vcxproj
Fix issue where the redistributable NuGet package isn't restored when listed as a package dependency of another package. Eg.
```XML
<group targetFramework="native0.0">
<dependency id="XDP-for-Windows-Runtime.x64" version="1.1.0" />
</group>  
```
This is due to the package not containing any content that targets the `native` target framework moniker (TFM). The package must contain at least one item group that specifies the `native` TFM, otherwise the dependency is silently ignored as the tooling doesn't detect any matching content.
Also fix issue where warnings generated during NuGet packing did not fail the build.
Fixes #822 #821
* Built new package locally, listed it as a dependency in a test project's `.nuspec` and validated the package was listed as a dependency in the dependent …
=> Fix minor NuGet packaging issues

src/xdpetw/xdpetw.man, src/xdplwf/recv.c, src/xdppcw/inc/xdppcw.h, src/xdppcw/xdppcw.man
Fix a race condition in xdp receive path in low resources scenario.
In low resource scenario, XDP must return the NBL chain unchanged to NDIS.
To do so, in `XdpGenericReceivePostInspectNbs`, it flushes NetBuffers that need to be passed to the next driver in `XdpGenericReceiveLowResources`, so it can re-assemble the NBL chain in order (if waiting as in the non-low resource path, in-order reassembly would become complex, since NBLs would be split between a "drop" and "pass" lists).
To optimize this logic, the code tries to indicate batches of NBLs when possible, by indicating a sequence of packets only when a packet needs to be dropped. The batch of NBLs is easy to put back in order: first all the indicated "PASS" NBLs, then the DROP NBL.
The following sequence of action should result in …
=> Fix a race condition in xdp receive path in low resources scenario

.github/workflows/ci.yml, src/xdp.props, test/spinxsk/spinxsk.c, test/spinxsk/spinxsk.vcxproj, test/xdpmp/xdpmp.md, tools/common.ps1, tools/prepare-machine.ps1, tools/spinxsk.ps1
Add FNMP support for spinxsk.
When using FNMP, spinxsk will inject randomized UDP frames on the receive path.
The following parameters are randomized:
- Address family: IPv4 / IPv6
- Data offset in NB
- Number of MBL (1 to 3)
- Local and remote port
- Whether to generate a QUIC header or not 
- Whether to use a TCP or UDP header
- Size of the UDP / TCP / QUIC payload
N/A
N/A
N/A
=> Use FNMP to inject interesting frames on the Rx path of spinxsk 

test/spinxsk/spinxsk.c
Fix a loop counter type flagged by code analysis.
The type was UINT8 and compared with a UINT32, potentially causing an infinite loop.
In practice, the value provided was always smaller than UINT8_MAX.
C/I
N/A
N/A
=> Fix loop counter type

docs/usage.md
PRs #589 and #623 changed our test-signing steps to use ephemeral certificates instead of the CoreNet certificate, but while the PR description for #623 provided sample steps to install the test-signed binaries, documentation was not updated.
Resolves #831 
N/A.
Yes.
No.
=> update test signed driver docs

src/nuget/nuget.vcxproj, src/xdpruntime/xdpruntime.vcxproj, tools/setup.ps1
Our internal build system requires NuGet packages be output to a `packages` subdirectory. Do that everywhere.
Builds locally. CI.
No.
No.
=> Output NuGet packages to a packages subdirectory

src/xdplwf/offload.c
When investigating failure to checksum offload in netperf for MsQuic, the XDP traces were missing some useful information about the NIC's actual advertised capabilities and configuration. This adds a backstop of logging the contents of all NDIS status indications handled by XDP.
CI.
No.
No.
=> Improve tracing of NDIS status indications

published/external/afxdp_experimental.h, published/external/xdpapi_experimental.h, src/xdplwf/offload.h, src/xdplwf/offloadtask.c, test/functional/lib/tests.cpp
Resolves #847. This is a breaking change and are intentionally not backward-compatible with previous iterations of this experimental/preview feature.
Minimal test case added.
Updated, within the headers.
No.
=> make tcp options optional in checksum offload

docs/api/XskGetSockopt.md, published/external/afxdp.h, published/external/xdp/afxdp_v1.h, published/external/xdp/details/afxdp.h, test/functional/lib/tests.cpp
While investigating our stress test failures in CI, I started code reviewing recent changes. I spotted a bug with how we handle zero-sized output buffers in getsockopt, which was intended to return the necessary output buffer size, but returned zero.
Tests added.
Yes, added.
No.
=> test and fix getsockopt behavior with zero-size output buffer

src/rtl/inc/xdprtl.h, src/xdp/programinspect.c, src/xdp/xsk.c
Add a few missing volatile accessors, including UMEM copies and XSK writes. Also, clarify the program inspection routine uses a volatile read of the mapped port bit set.
N.B. The standin RtlCopyVolatileMemory in XDP looks suspicious, and we should be compiling and linking against the real WDK version in official builds (we removed support for VS2019) so I removed it.
Compiles locally.
No.
No.
=> Add missing volatile accessors

Directory.Packages.props, src/xdp.props, src/xdpinstaller/xdpinstaller.wixproj
Our CI suddenly started failing to build the XDP installer project, which is known to be incompatible with the WDK. In the CI machines, because the WDK happens to be globally installed, it gets included whether or not we intentionally include the nuget version of the WDK. This global WDK also started breaking.
It seems like updating the WDK nuget to be at least as new as the WDK globally installed works around the problem, though I'm not sure it has been directly addressed.
CI.
No.
No.
=> Fix WDK build break

.github/workflows/build.yml
The global and nuget WDKs can race against each other in builds. The `/nodeReuse:false` is already used in build.ps1 for reliable but slightly slower builds.
CI.
No.
No.
=> Disable node reuse in all GitHub builds

.github/workflows/ci.yml
Release branches sometime have a different set of requirements that differ from non-release branches.
We don't want to block PRs on release branches due to some requirement in non-release branches that is irrelevant. 
Let's add logic to have a different set of dependencies depending on whether the branch is release or not.
CI
No.
No.
=> Add conditional requirements just for release branches
